language: python
# with next we get on container based infrastructure, this enables caching
sudo: false
python:
  - 2.7
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
# env:
#  - PLONE_VERSION=4.3.x SOLR_VERSION=4.10.x
#  - PLONE_VERSION=5.0.x SOLR_VERSION=4.10.x
#  - PLONE_VERSION=5.1.x SOLR_VERSION=4.10.x
#  - PLONE_VERSION=4.3.x SOLR_VERSION=5.1.x
#  - PLONE_VERSION=5.0.x SOLR_VERSION=5.1.x
#matrix:
#  allow_failures:
#    - env: PLONE_VERSION=4.3.x SOLR_VERSION=5.1.x
#    - env: PLONE_VERSION=5.0.x SOLR_VERSION=5.1.x
env:
  matrix:
    # - SOLR_VERSION=4.10.4
    # - SOLR_VERSION=5.2.1
    # - SOLR_VERSION=6.6.5
    # - SOLR_VERSION=7.2.1
    # - SOLR_VERSION=7.3.0
    - SOLR_VERSION=7.4.0
    - SOLR_VERSION=7.5.0
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - wget "http://chromedriver.storage.googleapis.com/2.44/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - virtualenv .
  - bin/pip install --upgrade -r requirements.txt
  - bin/pip install zest.pocompile
  - bin/pocompile src
install:
  # - sed -ie "s#plone-x.x.x.cfg#plone-$PLONE_VERSION.cfg#" travis.cfg
  # - sed -ie "s#solr-x.x.x.cfg#solr-$SOLR_VERSION.cfg#" travis.cfg
  - sed -ie "s#7.4.0#$SOLR_VERSION#" base.cfg
  - sed -ie "s#solr-7.4.0#solr-$SOLR_VERSION#" base.cfg
  - bin/buildout -N -t 20
script:
  - bin/code-analysis
  - bin/coverage run bin/test
  # Run Robot Framework in isolation to avoid test isolation issues.
  - export ROBOTSUITE_PREFIX=ONLYROBOT && bin/test -t ONLYROBOT --all
after_success:
  - pip install -q coveralls python-coveralls==2.5.0
  - coveralls
