os: linux
language: python
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
jobs:
  include:
    - python: 2.7
      env: PLONE_VERSION=4.3.x SOLR_VERSION=7.7.2 EXTRA_EGGS=collective.indexing
    - python: 2.7
      env: PLONE_VERSION=4.3.x SOLR_VERSION=8.2.0 EXTRA_EGGS=collective.indexing
    - python: 2.7
      env: PLONE_VERSION=5.1.x SOLR_VERSION=7.7.2 EXTRA_EGGS=
    - python: 2.7
      env: PLONE_VERSION=5.1.x SOLR_VERSION=8.2.0 EXTRA_EGGS=
    - python: 2.7
      env: PLONE_VERSION=5.2.x SOLR_VERSION=7.7.2 EXTRA_EGGS=
    - python: 2.7
      env: PLONE_VERSION=5.2.x SOLR_VERSION=8.2.0 EXTRA_EGGS=
    - python: 3.7
      env: PLONE_VERSION=5.2.x SOLR_VERSION=7.7.2 EXTRA_EGGS=
    - python: 3.7
      env: PLONE_VERSION=5.2.x SOLR_VERSION=8.2.0 EXTRA_EGGS=
dist: xenial
addons:
  chrome: stable
before_install:
  - wget "http://chromedriver.storage.googleapis.com/2.44/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - "export DISPLAY=:99.0"
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - virtualenv .
  - bin/pip install --upgrade -r requirements.txt
  - bin/pip install zest.pocompile
  - bin/pocompile src
install:
  - sed -ie "s#plone-.\..\.x\.cfg#plone-$PLONE_VERSION.cfg#" buildout.cfg
  - sed -ie "s#eggs +=#eggs += $EXTRA_EGGS#" buildout.cfg
  - sed -ie "s#solr/.\..\..#solr/$SOLR_VERSION#" base.cfg
  - sed -ie "s#solr-.\..\..#solr-$SOLR_VERSION#" base.cfg
  - cat base.cfg
  - cat buildout.cfg
  - bin/buildout -N -t 20
script:
  - bin/code-analysis
  - if [ -f "bin/black" ]; then bin/black src/ --check ; fi
  - bin/coverage run bin/test
  # Run Robot Framework in isolation to avoid test isolation issues.
  - export ROBOTSUITE_PREFIX=ONLYROBOT && bin/test -t ONLYROBOT --all
after_success:
  - pip install -q coveralls python-coveralls==2.5.0
  - coveralls
