language: python
# with next we get on container based infrastructure, this enables caching
sudo: false
python:
  - 2.7
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
env:
  - PLONE_VERSION=4.3.x SOLR_VERSION=4.10.x
  - PLONE_VERSION=5.0.x SOLR_VERSION=4.10.x
  - PLONE_VERSION=5.1.x SOLR_VERSION=4.10.x
#  - PLONE_VERSION=4.3.x SOLR_VERSION=5.1.x
#  - PLONE_VERSION=5.0.x SOLR_VERSION=5.1.x
#matrix:
#  allow_failures:
#    - env: PLONE_VERSION=4.3.x SOLR_VERSION=5.1.x
#    - env: PLONE_VERSION=5.0.x SOLR_VERSION=5.1.x
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - virtualenv .
  - bin/pip install --upgrade pip setuptools zc.buildout zest.pocompile
  - bin/pocompile src
install:
  - sed -ie "s#plone-x.x.x.cfg#plone-$PLONE_VERSION.cfg#" travis.cfg
  - sed -ie "s#solr-x.x.x.cfg#solr-$SOLR_VERSION.cfg#" travis.cfg
  - bin/buildout -N -t 20 -c travis.cfg
script:
  - bin/code-analysis
  - bin/coverage run bin/test
  # Run Robot Framework in isolation to avoid test isolation issues.
  - export ROBOTSUITE_PREFIX=ONLYROBOT && bin/test -t ONLYROBOT --all
after_success:
  - pip install -q coveralls python-coveralls==2.5.0
  - coveralls
